//TEMAS POSIBLES
const DUMMY_THEMES =
    'Beginner Friendly,Open Ended,Social Good,Machine Learning/AI,Low/No Code,Web,Education,Design,IoT,Enterprise,Databases,Blockchain,Productivity,Gaming';

//TECNOLOGÍAS POSIBLES
const DUMMY_TECHNOLOGIES =
    'HTML,CSS,JAVASCRIPT,SQL,PYTHON,JAVA,PHP,HOW TO,W3.CSS,C,C++,C#,BOOTSTRAP,REACT,MYSQL,JQUERY,EXCEL,XML,DJANGO,NUMPY,PANDAS,NODEJS,R,TYPESCRIPT,ANGULAR,GIT,POSTGRESQL,MONGODB,ASP,AI,GO,KOTLIN,SASS,VUE,DSA,GEN AI,SCIPY,AWS,CYBERSECURITY,DATA SCIENCE';

export { DUMMY_TECHNOLOGIES, DUMMY_THEMES };
