const users = [
    {
        id: 1,
        username: 'devUser1',
        email: 'dev1@example.com',
        password: 'password1',
        avatar: 'avatar1.png',
        firstName: 'John',
        lastName: 'Doe',
        role: 'desarrollador',
        biography: 'Desarrollador apasionado por la tecnología.',
        linkedIn: 'https://linkedin.com/in/devUser1',
    },
    {
        id: 2,
        username: 'orgUser1',
        email: 'org1@example.com',
        password: 'password2',
        avatar: 'avatar2.png',
        firstName: 'Jane',
        lastName: 'Smith',
        role: 'organizador',
        biography: 'Organizadora de eventos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/orgUser1',
    },
    {
        id: 3,
        username: 'devUser2',
        email: 'dev2@example.com',
        password: 'password3',
        avatar: 'avatar3.png',
        firstName: 'Alice',
        lastName: 'Johnson',
        role: 'desarrollador',
        biography: 'Desarrolladora con experiencia en hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser2',
    },
    {
        id: 4,
        username: 'devUser3',
        email: 'dev3@example.com',
        password: 'password4',
        avatar: 'avatar4.png',
        firstName: 'Bob',
        lastName: 'Brown',
        role: 'desarrollador',
        biography: 'Entusiasta de la programación y la tecnología.',
        linkedIn: 'https://linkedin.com/in/devUser3',
    },
    {
        id: 5,
        username: 'devUser4',
        email: 'dev4@example.com',
        password: 'password5',
        avatar: 'avatar5.png',
        firstName: 'Charlie',
        lastName: 'Davis',
        role: 'desarrollador',
        biography: 'Desarrollador con pasión por los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser4',
    },
    {
        id: 6,
        username: 'devUser5',
        email: 'dev5@example.com',
        password: 'password6',
        avatar: 'avatar6.png',
        firstName: 'David',
        lastName: 'Evans',
        role: 'desarrollador',
        biography: 'Amante de la tecnología y la innovación.',
        linkedIn: 'https://linkedin.com/in/devUser5',
    },
    {
        id: 7,
        username: 'devUser6',
        email: 'dev6@example.com',
        password: 'password7',
        avatar: 'avatar7.png',
        firstName: 'Eve',
        lastName: 'Foster',
        role: 'desarrollador',
        biography: 'Desarrolladora con interés en proyectos innovadores.',
        linkedIn: 'https://linkedin.com/in/devUser6',
    },
    {
        id: 8,
        username: 'devUser7',
        email: 'dev7@example.com',
        password: 'password8',
        avatar: 'avatar8.png',
        firstName: 'Frank',
        lastName: 'Garcia',
        role: 'desarrollador',
        biography: 'Apasionado por la programación y los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser7',
    },
    {
        id: 9,
        username: 'devUser8',
        email: 'dev8@example.com',
        password: 'password9',
        avatar: 'avatar9.png',
        firstName: 'Grace',
        lastName: 'Harris',
        role: 'desarrollador',
        biography: 'Desarrolladora con experiencia en proyectos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/devUser8',
    },
    {
        id: 10,
        username: 'devUser9',
        email: 'dev9@example.com',
        password: 'password10',
        avatar: 'avatar10.png',
        firstName: 'Hank',
        lastName: 'Irvine',
        role: 'desarrollador',
        biography: 'Entusiasta de la tecnología y la programación.',
        linkedIn: 'https://linkedin.com/in/devUser9',
    },
    {
        id: 11,
        username: 'devUser10',
        email: 'dev10@example.com',
        password: 'password11',
        avatar: 'avatar11.png',
        firstName: 'Ivy',
        lastName: 'Jones',
        role: 'desarrollador',
        biography: 'Desarrolladora con pasión por los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser10',
    },
    {
        id: 12,
        username: 'devUser11',
        email: 'dev11@example.com',
        password: 'password12',
        avatar: 'avatar12.png',
        firstName: 'Jack',
        lastName: 'King',
        role: 'desarrollador',
        biography: 'Amante de la tecnología y la innovación.',
        linkedIn: 'https://linkedin.com/in/devUser11',
    },
    {
        id: 13,
        username: 'devUser12',
        email: 'dev12@example.com',
        password: 'password13',
        avatar: 'avatar13.png',
        firstName: 'Kate',
        lastName: 'Lewis',
        role: 'desarrollador',
        biography: 'Desarrolladora con interés en proyectos innovadores.',
        linkedIn: 'https://linkedin.com/in/devUser12',
    },
    {
        id: 14,
        username: 'devUser13',
        email: 'dev13@example.com',
        password: 'password14',
        avatar: 'avatar14.png',
        firstName: 'Leo',
        lastName: 'Martinez',
        role: 'desarrollador',
        biography: 'Apasionado por la programación y los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser13',
    },
    {
        id: 15,
        username: 'devUser14',
        email: 'dev14@example.com',
        password: 'password15',
        avatar: 'avatar15.png',
        firstName: 'Mia',
        lastName: 'Nelson',
        role: 'desarrollador',
        biography: 'Desarrolladora con experiencia en proyectos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/devUser14',
    },
    {
        id: 16,
        username: 'devUser15',
        email: 'dev15@example.com',
        password: 'password16',
        avatar: 'avatar16.png',
        firstName: 'Nate',
        lastName: 'Owens',
        role: 'desarrollador',
        biography: 'Entusiasta de la tecnología y la programación.',
        linkedIn: 'https://linkedin.com/in/devUser15',
    },
    {
        id: 17,
        username: 'devUser16',
        email: 'dev16@example.com',
        password: 'password17',
        avatar: 'avatar17.png',
        firstName: 'Olivia',
        lastName: 'Parker',
        role: 'desarrollador',
        biography: 'Desarrolladora con pasión por los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser16',
    },
    {
        id: 18,
        username: 'devUser17',
        email: 'dev17@example.com',
        password: 'password18',
        avatar: 'avatar18.png',
        firstName: 'Paul',
        lastName: 'Quinn',
        role: 'desarrollador',
        biography: 'Amante de la tecnología y la innovación.',
        linkedIn: 'https://linkedin.com/in/devUser17',
    },
    {
        id: 19,
        username: 'devUser18',
        email: 'dev18@example.com',
        password: 'password19',
        avatar: 'avatar19.png',
        firstName: 'Quinn',
        lastName: 'Reed',
        role: 'desarrollador',
        biography: 'Desarrollador con interés en proyectos innovadores.',
        linkedIn: 'https://linkedin.com/in/devUser18',
    },
    {
        id: 20,
        username: 'devUser19',
        email: 'dev19@example.com',
        password: 'password20',
        avatar: 'avatar20.png',
        firstName: 'Rachel',
        lastName: 'Scott',
        role: 'desarrollador',
        biography: 'Entusiasta de la tecnología y la programación.',
        linkedIn: 'https://linkedin.com/in/devUser19',
    },
    {
        id: 21,
        username: 'devUser20',
        email: 'dev20@example.com',
        password: 'password21',
        avatar: 'avatar21.png',
        firstName: 'Sam',
        lastName: 'Taylor',
        role: 'desarrollador',
        biography: 'Desarrollador con pasión por los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser20',
    },
    {
        id: 22,
        username: 'devUser21',
        email: 'dev21@example.com',
        password: 'password22',
        avatar: 'avatar22.png',
        firstName: 'Tina',
        lastName: 'Upton',
        role: 'desarrollador',
        biography: 'Amante de la tecnología y la innovación.',
        linkedIn: 'https://linkedin.com/in/devUser21',
    },
    {
        id: 23,
        username: 'devUser22',
        email: 'dev22@example.com',
        password: 'password23',
        avatar: 'avatar23.png',
        firstName: 'Victor',
        lastName: 'Vega',
        role: 'desarrollador',
        biography: 'Desarrollador con interés en proyectos innovadores.',
        linkedIn: 'https://linkedin.com/in/devUser22',
    },
    {
        id: 24,
        username: 'devUser23',
        email: 'dev23@example.com',
        password: 'password24',
        avatar: 'avatar24.png',
        firstName: 'Wendy',
        lastName: 'White',
        role: 'desarrollador',
        biography: 'Apasionada por la programación y los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser23',
    },
    {
        id: 25,
        username: 'devUser24',
        email: 'dev24@example.com',
        password: 'password25',
        avatar: 'avatar25.png',
        firstName: 'Xander',
        lastName: 'Xavier',
        role: 'desarrollador',
        biography: 'Desarrollador con experiencia en proyectos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/devUser24',
    },
    {
        id: 26,
        username: 'devUser25',
        email: 'dev25@example.com',
        password: 'password26',
        avatar: 'avatar26.png',
        firstName: 'Yara',
        lastName: 'Young',
        role: 'desarrollador',
        biography: 'Entusiasta de la tecnología y la programación.',
        linkedIn: 'https://linkedin.com/in/devUser25',
    },
    {
        id: 27,
        username: 'devUser26',
        email: 'dev26@example.com',
        password: 'password27',
        avatar: 'avatar27.png',
        firstName: 'Zane',
        lastName: 'Zimmerman',
        role: 'desarrollador',
        biography: 'Desarrollador con pasión por los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser26',
    },
    {
        id: 28,
        username: 'devUser27',
        email: 'dev27@example.com',
        password: 'password28',
        avatar: 'avatar28.png',
        firstName: 'Aaron',
        lastName: 'Adams',
        role: 'desarrollador',
        biography: 'Amante de la tecnología y la innovación.',
        linkedIn: 'https://linkedin.com/in/devUser27',
    },
    {
        id: 29,
        username: 'devUser28',
        email: 'dev28@example.com',
        password: 'password29',
        avatar: 'avatar29.png',
        firstName: 'Bella',
        lastName: 'Baker',
        role: 'desarrollador',
        biography: 'Desarrolladora con interés en proyectos innovadores.',
        linkedIn: 'https://linkedin.com/in/devUser28',
    },
    {
        id: 30,
        username: 'devUser29',
        email: 'dev29@example.com',
        password: 'password30',
        avatar: 'avatar30.png',
        firstName: 'Chris',
        lastName: 'Carter',
        role: 'desarrollador',
        biography: 'Apasionado por la programación y los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser29',
    },
    {
        id: 31,
        username: 'devUser30',
        email: 'dev30@example.com',
        password: 'password31',
        avatar: 'avatar31.png',
        firstName: 'Dana',
        lastName: 'Dixon',
        role: 'desarrollador',
        biography: 'Desarrolladora con experiencia en proyectos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/devUser30',
    },
    {
        id: 32,
        username: 'devUser31',
        email: 'dev31@example.com',
        password: 'password32',
        avatar: 'avatar32.png',
        firstName: 'Eli',
        lastName: 'Edwards',
        role: 'desarrollador',
        biography: 'Entusiasta de la tecnología y la programación.',
        linkedIn: 'https://linkedin.com/in/devUser31',
    },
    {
        id: 33,
        username: 'devUser32',
        email: 'dev32@example.com',
        password: 'password33',
        avatar: 'avatar33.png',
        firstName: 'Fiona',
        lastName: 'Fisher',
        role: 'desarrollador',
        biography: 'Desarrolladora con pasión por los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser32',
    },
    {
        id: 34,
        username: 'devUser33',
        email: 'dev33@example.com',
        password: 'password34',
        avatar: 'avatar34.png',
        firstName: 'George',
        lastName: 'Gonzalez',
        role: 'desarrollador',
        biography: 'Amante de la tecnología y la innovación.',
        linkedIn: 'https://linkedin.com/in/devUser33',
    },
    {
        id: 35,
        username: 'devUser34',
        email: 'dev34@example.com',
        password: 'password35',
        avatar: 'avatar35.png',
        firstName: 'Hannah',
        lastName: 'Hughes',
        role: 'desarrollador',
        biography: 'Desarrolladora con interés en proyectos innovadores.',
        linkedIn: 'https://linkedin.com/in/devUser34',
    },
    {
        id: 36,
        username: 'devUser35',
        email: 'dev35@example.com',
        password: 'password36',
        avatar: 'avatar36.png',
        firstName: 'Ian',
        lastName: 'Ingram',
        role: 'desarrollador',
        biography: 'Apasionado por la programación y los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser35',
    },
    {
        id: 37,
        username: 'devUser36',
        email: 'dev36@example.com',
        password: 'password37',
        avatar: 'avatar37.png',
        firstName: 'Jill',
        lastName: 'Jackson',
        role: 'desarrollador',
        biography: 'Desarrolladora con experiencia en proyectos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/devUser36',
    },
    {
        id: 38,
        username: 'devUser37',
        email: 'dev37@example.com',
        password: 'password38',
        avatar: 'avatar38.png',
        firstName: 'Kyle',
        lastName: 'Klein',
        role: 'desarrollador',
        biography: 'Entusiasta de la tecnología y la programación.',
        linkedIn: 'https://linkedin.com/in/devUser37',
    },
    {
        id: 39,
        username: 'devUser38',
        email: 'dev38@example.com',
        password: 'password39',
        avatar: 'avatar39.png',
        firstName: 'Liam',
        lastName: 'Miller',
        role: 'desarrollador',
        biography: 'Apasionado por la programación y los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser38',
    },
    {
        id: 40,
        username: 'devUser39',
        email: 'dev39@example.com',
        password: 'password40',
        avatar: 'avatar40.png',
        firstName: 'Mona',
        lastName: 'Nash',
        role: 'desarrollador',
        biography: 'Desarrolladora con experiencia en proyectos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/devUser39',
    },
    {
        id: 41,
        username: 'devUser40',
        email: 'dev40@example.com',
        password: 'password41',
        avatar: 'avatar41.png',
        firstName: 'Nina',
        lastName: 'Olsen',
        role: 'desarrollador',
        biography: 'Entusiasta de la tecnología y la programación.',
        linkedIn: 'https://linkedin.com/in/devUser40',
    },
    {
        id: 42,
        username: 'devUser41',
        email: 'dev41@example.com',
        password: 'password42',
        avatar: 'avatar42.png',
        firstName: 'Oscar',
        lastName: 'Perez',
        role: 'desarrollador',
        biography: 'Desarrollador con pasión por los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser41',
    },
    {
        id: 43,
        username: 'devUser42',
        email: 'dev42@example.com',
        password: 'password43',
        avatar: 'avatar43.png',
        firstName: 'Paula',
        lastName: 'Quinn',
        role: 'desarrollador',
        biography: 'Amante de la tecnología y la innovación.',
        linkedIn: 'https://linkedin.com/in/devUser42',
    },
    {
        id: 44,
        username: 'devUser43',
        email: 'dev43@example.com',
        password: 'password44',
        avatar: 'avatar44.png',
        firstName: 'Quincy',
        lastName: 'Reed',
        role: 'desarrollador',
        biography: 'Desarrollador con interés en proyectos innovadores.',
        linkedIn: 'https://linkedin.com/in/devUser43',
    },
    {
        id: 45,
        username: 'devUser44',
        email: 'dev44@example.com',
        password: 'password45',
        avatar: 'avatar45.png',
        firstName: 'Rachel',
        lastName: 'Scott',
        role: 'desarrollador',
        biography: 'Apasionada por la programación y los hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser44',
    },
    {
        id: 46,
        username: 'orgUser2',
        email: 'org2@example.com',
        password: 'password46',
        avatar: 'avatar46.png',
        firstName: 'Sam',
        lastName: 'Taylor',
        role: 'organizador',
        biography: 'Organizador de eventos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/orgUser2',
    },
    {
        id: 47,
        username: 'orgUser3',
        email: 'org3@example.com',
        password: 'password47',
        avatar: 'avatar47.png',
        firstName: 'Tina',
        lastName: 'Upton',
        role: 'organizador',
        biography: 'Organizadora de hackathons y eventos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/orgUser3',
    },
    {
        id: 48,
        username: 'orgUser4',
        email: 'org4@example.com',
        password: 'password48',
        avatar: 'avatar48.png',
        firstName: 'Victor',
        lastName: 'Vega',
        role: 'organizador',
        biography: 'Organizador con experiencia en eventos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/orgUser4',
    },
    {
        id: 49,
        username: 'orgUser5',
        email: 'org5@example.com',
        password: 'password49',
        avatar: 'avatar49.png',
        firstName: 'Wendy',
        lastName: 'White',
        role: 'organizador',
        biography: 'Apasionada por la organización de eventos.',
        linkedIn: 'https://linkedin.com/in/orgUser5',
    },
    {
        id: 50,
        username: 'orgUser6',
        email: 'org6@example.com',
        password: 'password50',
        avatar: 'avatar50.png',
        firstName: 'Xander',
        lastName: 'Xavier',
        role: 'organizador',
        biography: 'Organizador de eventos con experiencia en hackathons.',
        linkedIn: 'https://linkedin.com/in/orgUser6',
    },
    {
        id: 51,
        username: 'orgUser7',
        email: 'org7@example.com',
        password: 'password51',
        avatar: 'avatar51.png',
        firstName: 'Yara',
        lastName: 'Young',
        role: 'organizador',
        biography: 'Entusiasta de la organización de eventos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/orgUser7',
    },
    {
        id: 52,
        username: 'orgUser8',
        email: 'org8@example.com',
        password: 'password52',
        avatar: 'avatar52.png',
        firstName: 'Zane',
        lastName: 'Zimmerman',
        role: 'organizador',
        biography: 'Organizador con pasión por los eventos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/orgUser8',
    },
    {
        id: 53,
        username: 'orgUser9',
        email: 'org9@example.com',
        password: 'password53',
        avatar: 'avatar53.png',
        firstName: 'Aaron',
        lastName: 'Adams',
        role: 'organizador',
        biography: 'Amante de la organización de eventos y hackathons.',
        linkedIn: 'https://linkedin.com/in/orgUser9',
    },
    {
        id: 54,
        username: 'orgUser10',
        email: 'org10@example.com',
        password: 'password54',
        avatar: 'avatar54.png',
        firstName: 'Bella',
        lastName: 'Baker',
        role: 'organizador',
        biography: 'Organizadora con interés en eventos innovadores.',
        linkedIn: 'https://linkedin.com/in/orgUser10',
    },
    {
        id: 55,
        username: 'orgUser11',
        email: 'org11@example.com',
        password: 'password55',
        avatar: 'avatar55.png',
        firstName: 'Chris',
        lastName: 'Carter',
        role: 'organizador',
        biography: 'Apasionado por la organización de hackathons.',
        linkedIn: 'https://linkedin.com/in/orgUser11',
    },
    {
        id: 56,
        username: 'orgUser12',
        email: 'org12@example.com',
        password: 'password56',
        avatar: 'avatar56.png',
        firstName: 'Dana',
        lastName: 'Dixon',
        role: 'organizador',
        biography: 'Organizadora con experiencia en eventos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/orgUser12',
    },
    {
        id: 57,
        username: 'orgUser13',
        email: 'org13@example.com',
        password: 'password57',
        avatar: 'avatar57.png',
        firstName: 'Eli',
        lastName: 'Edwards',
        role: 'organizador',
        biography: 'Entusiasta de la organización de eventos y hackathons.',
        linkedIn: 'https://linkedin.com/in/orgUser13',
    },
    {
        id: 58,
        username: 'orgUser14',
        email: 'org14@example.com',
        password: 'password58',
        avatar: 'avatar58.png',
        firstName: 'Fiona',
        lastName: 'Fisher',
        role: 'organizador',
        biography: 'Organizadora con pasión por eventos tecnológicos.',
        linkedIn: 'https://linkedin.com/in/orgUser14',
    },
    {
        id: 59,
        username: 'orgUser15',
        email: 'org15@example.com',
        password: 'password59',
        avatar: 'avatar59.png',
        firstName: 'George',
        lastName: 'Gonzalez',
        role: 'organizador',
        biography: 'Organizador con experiencia en hackathons.',
        linkedIn: 'https://linkedin.com/in/orgUser15',
    },
    {
        id: 60,
        username: 'devUser45',
        email: 'dev45@example.com',
        password: 'password60',
        avatar: 'avatar60.png',
        firstName: 'Alice',
        lastName: 'Johnson',
        role: 'desarrollador',
        biography: 'Desarrolladora con experiencia en hackathons.',
        linkedIn: 'https://linkedin.com/in/devUser45',
    },
];

export default users;
